services:
  workflow-app:
    container_name: symfony-workflow-app
    build:
      context: ./
      dockerfile: workflow-app/Dockerfile
      args:
        - PHP_USER=temporal
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
     - ../../../symfony/workflow-app:/var/www
    environment:
      - TEMPORAL_TASK_QUEUE=temporal.symfony.queue
      - TEMPORAL_SERVER_ENDPOINT=temporal.addr:7233
      - TELEMETRY_DRIVER=otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.addr:4318
      - OTEL_PHP_TRACES_PROCESSOR=simple
      - TEMPORAL_HOST=temporal.addr
      - OTEL_HOST=collector.addr
      - OTEL_SERVICE_NAME=symfony-workflow-app
    networks:
      - temporal-symfony-mono
    ports:
      - 9305:80
    extra_hosts:
      - "temporal.addr=host-gateway"
      - "collector.addr=host-gateway"

  # frankenphp:
  #   container_name: frankenphp-app
  #   build:
  #     context: ./
  #     dockerfile: frankenphp/Dockerfile
  #     args:
  #       - PHP_USER=temporal
  #       - PHP_UID=${PHP_UID:-1000}
  #       - PHP_GID=${PHP_GID:-1000}
  #   volumes:
  #    - ../../../symfony/workflow-api:/app/public
  #   environment:
  #     - TEMPORAL_TASK_QUEUE=temporal.symfony.queue
  #     - TEMPORAL_SERVER_ENDPOINT=temporal.addr:7233
  #     - TELEMETRY_DRIVER=otel
  #     - OTEL_TRACES_EXPORTER=otlp
  #     - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.addr:4318
  #     - OTEL_PHP_TRACES_PROCESSOR=simple
  #     - TEMPORAL_HOST=temporal.addr
  #     - OTEL_HOST=collector.addr
  #     - OTEL_SERVICE_NAME=symfony-workflow-ap1
  #   networks:
  #     - temporal-symfony-mono
  #   ports:
  #     - 9306:80

networks:
  temporal-symfony-mono:
    driver: bridge
    name: temporal-symfony-mono
